config/routes.rb
Rails.application.routes.draw do
  root 'links#index'
  resources :links, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :users, only: [:new, :create, :update]
  get '/login', to: "session#new"
  post '/login', to: "session#create"
  delete '/logout', to: "session#destroy"
  namespace :api do
    namespace :v1 do
      resources :links, only: [:index, :update], defaults: { format: :json }
    end
  end

  get '*path', to: 'links#index'
end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :user
  validates :url, :url => true,
                  presence: true
  validates :title, presence: true

  def fetch_summary(params)
    url = params['url']
    Page.get(url).css("meta[name='description']").first.attributes['content'].value
    rescue HTTParty::Error
    rescue StandardError
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :links

  validates :email, presence: true,
                    uniqueness: true

  validates :password, presence: true

  def password_match(params)
    params[:password] == params[:confirm_password]
  end
end

app/controllers/api/v1/links_controller.rb
class Api::V1::LinksController < ApplicationController
  respond_to :json

  def index
    links = current_user.links.all
    respond_with links
  end

  def update
    link = current_user.links.find(params[:id])
    link.update(link_params)
    respond_with link, json: link
  end

  private

  def link_params
    params.permit(:id, :title, :url, :read)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def index
    if current_user
      @link = current_user.links.new
      @links = current_user.links.all
    end
  end

  def create
    @link = current_user.links.new(link_params)
    url_meta_content = @link.fetch_summary(link_params)
    @link.summary = url_meta_content
    if @link.save
      redirect_to root_path
    else
      flash[:error] = "Something went wrong. Please try again."
      redirect_to root_path
    end
  end

  def edit
    @link = current_user.links.find(params[:id])
  end

  def update
    @link = current_user.links.find(params[:id])
    @link.update(link_params)
    url_meta_content = @link.fetch_summary(link_params)
    @link.summary = url_meta_content
    if @link.save
      redirect_to root_path
    else
      flash[:error] = "Something went wrong. Try again."
      redirect_to root_path
    end
  end

  private

  def link_params
    params.require(:link).permit(:title,
                                 :url,
                                 :read,
                                 :id)
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email])
    if @user
      if @user && @user.authenticate(params[:session][:password])
        session[:user_id] = @user.id
        redirect_to root_path
      else
        flash.now[:error] = "Invalid email or password. Try again."
        render :new
      end
    else
      flash[:errors] = "Please create account first"
      redirect_to login_path
    end
  end

  def destroy
    session.clear
    flash[:logout] = "Goodbye!"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.password_match(user_params)
      if @user.save
        session[:user_id] = @user.id
        flash[:notice] = "Logged in as #{@user.email}"
        redirect_to root_path
      else
        flash.now[:error] = "Something went wrong. Please try again."
        render :new
      end
    else
      flash.now[:error] = "Something went wrong. Please try again."
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email,
                                 :password,
                                 :confirm_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/link_helper.rb
module LinkHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FinalSpinboard</title>
  <%= stylesheet_link_tag    'custom', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

    <% if flash[:success] %>
      <!-- <div id="nav-bar" class="green lighten-2 alert white-text"> -->
      <p><%= raw(flash[:success]) %></p>
      <!-- </div> -->
    <% else %>
      <!-- <div id="nav-bar" class="blue lighten-2 alert white-text"> -->
      <% flash.each do |type, message| %>
        <p><%= content_tag(:div, message) %></p>
      <% end %>
      <!-- </div> -->
    <% end %>

<%= yield %>


</body>
</html>

app/views/links/edit.html.erb
<h3>Edit Link</h3>

<%= form_for(@link, :url => {:action => "update", :id => @link.id}) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :url %>
  <%= f.text_field :url %>
  <%= f.submit "Update Link" %>
<% end %>

app/views/links/index.html.erb
<% if current_user %>
  <%= link_to "Sign Out", logout_path, method: :delete %>

  <h3>New Link</h3>

  <%= form_for(@link) do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :url %>
    <%= f.text_field :url %>
    <%= f.submit "Add Link" %>
  <% end %>

  <h3>Your Links</h3>

  <div class="filter" id=link_filter_title>
    <label for="link_filter_title">Search: </label>
    <%= text_field_tag :search_by_title%>
  </div>

  <button id="view-read-links">View Read Links</button>
  <button id="view-unread-links">View Unread Links</button>

  <button id="filter-list-by-status">Filter List By Status</button>

  <button id="filter-list-alphabetically">Filter List Alphabetically</button>

  <div id="link-info" class="clearfix">

  </div>

<% else %>
  <%= link_to "Sign In", login_path %>
  <%= link_to "Sign Up", new_user_path %>
<% end %>

app/views/session/new.html.erb
<%= link_to "Create Account", new_user_path %>
<h1>Login</h1>

<%= form_for(:session, url: login_path) do |f| %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.submit "Login" %>
<% end %>

app/views/users/new.html.erb
<%= link_to "Sign In", login_path %>

<h1>Create Account</h1>

<%= form_for(@user) do |f| %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :confirm_password %>
  <%= f.password_field :confirm_password %>
  <%= f.submit "Create Account" %>
<% end %>